name = "Vanillium-Client"
author = "Nodev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dc30d29aca48ab0da75746ac3d2b1919025eafb34e6ec85b4b9019d9e3be841"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = "1.21"
