name = "Vanillium"
author = "Nodev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b6132389960be99ce3c383bb7353852acbc91887e86f9f0eb6c568bf60f971a"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = "1.21"
