name = "Vanillium-Client"
author = "Nodev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e45f82c71cb4acf40d41b42d502b50bff4c8623c10ce0c2275853e8d6938eda2"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = "1.21"
